export const data = [
  {
    id: 1,
    logo: "logo.png",
    title: "Full Stack Developer",
    pay: "$400k - $500k",
    location: "New Yourk, USA",
    skills: ["React", "Node", "MongoDB"],
    views: 500,
    applied: 200,
  },
  {
    id: 2,
    logo: "logo.png",
    title: "UI/UX Designer",
    pay: "$100k - $200k",
    location: "New Yourk, USA",
    skills: ["React", "Node", "MongoDB"],
    views: 500,
    applied: 200,
  },
  {
    id: 3,
    logo: "logo.png",
    title: "Back End Developer",
    pay: "$300k - $500k",
    location: "New Yourk, USA",
    skills: ["React", "Node", "MongoDB"],
    views: 500,
    applied: 200,
  },
  {
    id: 4,
    logo: "logo.png",
    title: "Front End Developer",
    pay: "$40k - $100k",
    location: "New Yourk, USA",
    skills: ["React", "Node", "MongoDB"],
    views: 500,
    applied: 200,
  },
  {
    id: 5,
    logo: "logo.png",
    title: "Front End Developer",
    pay: "$400k - $500k",
    location: "New Yourk, USA",
    skills: ["React", "Node", "MongoDB"],
    views: 500,
    applied: 200,
  },
];
